# Generated by Django 4.0 on 2021-12-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipe_rating_alter_recipe_activetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
