# Generated by Django 4.0 on 2022-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayName',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
