# Generated by Django 4.0 on 2022-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
