# Generated by Django 4.0 on 2022-01-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='displayName',
        ),
    ]
